"""
Transform Synthesizer — Generates new transforms for target domains.

When the TransferEngine discovers that a structural role (e.g., "identity")
exists in arithmetic but not in logic, this module GENERATES the actual
graph-rewrite code for the target domain.

Algorithm:
  1. Take a source transform exemplar (e.g., AddZeroElimination)
  2. Extract its structural skeleton: binary_op(X, neutral_element) → X
  3. Instantiate skeleton with target domain operators:
     - arithmetic identity: +(x, 0) → x
     - logic identity: AND(p, True) → p
     - set identity: UNION(X, ∅) → X
  4. Build a new Transform class from the instantiated skeleton
  5. Test it on known problems
  6. Promote if it works

This is the key missing piece: going from "these domains share structure"
to "here's a working rule for the new domain."
"""

from __future__ import annotations

import logging
import time
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

log = logging.getLogger(__name__)

_PERSIST_PATH = Path(__file__).resolve().parents[3] / "data" / "memory" / "synthesized_transforms.json"


# ═══════════════════════════════════════════════════════════════════════════════
#  Domain Knowledge: operator → neutral/absorbing elements
# ═══════════════════════════════════════════════════════════════════════════════

# This is the MINIMAL bootstrap: which operators exist in which domains,
# and what their identity/absorbing elements are. This IS domain knowledge
# but it's structural, not rule-specific — the RULES are synthesized.

# Map curriculum domain names to DOMAIN_OPERATORS keys
DOMAIN_NAME_MAP = {
    "logic_basics": "logic",
    "set_theory": "sets",
    "arithmetic": "arithmetic",
    "algebra": "arithmetic",
    "distribution": "arithmetic",
    "factoring": "arithmetic",
    "linear_equations": "arithmetic",
    "constant_arithmetic": "arithmetic",
    "combining_terms": "arithmetic",
    "identity_basics": "arithmetic",
    "annihilation": "arithmetic",
    "negation": "arithmetic",
    "power_rules": "arithmetic",
    "cancellation_patterns": "arithmetic",
    "complex_simplification": "arithmetic",
    "trigonometry": "trigonometry",
    "calculus": "calculus",
    "probability": "probability",
}

def map_domain_name(domain: str) -> str:
    """Map curriculum domain name to DOMAIN_OPERATORS key."""
    return DOMAIN_NAME_MAP.get(domain, domain)

# The raw domain knowledge (operators, identities) is now dynamically provided by the LLMWorldModel
# via the LLMBridge, rather than being hardcoded here.


# ═══════════════════════════════════════════════════════════════════════════════
#  Structural Skeletons for each role
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class TransformSkeleton:
    """Abstract template for a structural role."""
    role: str
    description: str
    requires: str          # "identity", "absorbing", "involution", etc.
    match_template: str    # how to match: "binary_op_with_{element}_child"
    rewrite_template: str  # what to do: "replace_with_other_child", "replace_with_{element}"


SKELETONS = {
    "identity": TransformSkeleton(
        role="identity",
        description="op(x, identity_element) → x",
        requires="identity",
        match_template="binary_op_with_identity_child",
        rewrite_template="replace_with_other_child",
    ),
    "annihilation": TransformSkeleton(
        role="annihilation",
        description="op(x, absorbing_element) → absorbing_element",
        requires="absorbing",
        match_template="binary_op_with_absorbing_child",
        rewrite_template="replace_with_absorbing",
    ),
    "involution": TransformSkeleton(
        role="involution",
        description="f(f(x)) → x (double application cancels)",
        requires="involution",
        match_template="double_unary_application",
        rewrite_template="unwrap_double",
    ),
    "self_inverse": TransformSkeleton(
        role="self_inverse",
        description="op(x, x) → identity_element",
        requires="identity",
        match_template="binary_op_same_operands",
        rewrite_template="replace_with_identity",
    ),
}


# ═══════════════════════════════════════════════════════════════════════════════
#  Synthesized Transform (runtime-generated)
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class SynthesizedTransform:
    """A transform generated by the synthesizer."""
    name: str
    domain: str
    role: str
    operator_labels: List[str]    # which graph labels to match
    element_label: str            # identity/absorbing element label
    rewrite_action: str           # what to do on match
    confidence: float = 0.5
    test_results: List[dict] = field(default_factory=list)
    promoted: bool = False
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return {
            "name": self.name, "domain": self.domain, "role": self.role,
            "operators": self.operator_labels, "element": self.element_label,
            "rewrite": self.rewrite_action, "confidence": round(self.confidence, 3),
            "promoted": self.promoted, "tests": len(self.test_results),
        }


def _make_runtime_transform(spec: SynthesizedTransform):
    """
    Generate a live Transform instance from a SynthesizedTransform spec.
    Returns a Transform subclass instance that can be used in BeamSearch.
    """
    from sare.engine import Transform, Graph

    class SynthTransform(Transform):
        def __init__(self, s):
            self._spec = s
        def name(self):
            return self._spec.name

        def match(self, graph):
            matches = []
            op_labels = set(self._spec.operator_labels)
            element = self._spec.element_label

            if self._spec.rewrite_action == "replace_with_other_child":
                # Identity pattern: op(x, element) → x
                for n in graph.nodes:
                    if n.type == "operator" and n.label in op_labels:
                        children = graph.outgoing(n.id)
                        if len(children) != 2:
                            continue
                        c1 = graph.get_node(children[0].target)
                        c2 = graph.get_node(children[1].target)
                        for el, other in [(c1, c2), (c2, c1)]:
                            if (el and other and el.type == "constant"
                                    and el.label == element):
                                matches.append({
                                    "op": n.id, "element": el.id, "other": other.id
                                })
                                break

            elif self._spec.rewrite_action == "replace_with_absorbing":
                # Annihilation: op(x, absorbing) → absorbing
                for n in graph.nodes:
                    if n.type == "operator" and n.label in op_labels:
                        children = graph.outgoing(n.id)
                        for e in children:
                            child = graph.get_node(e.target)
                            if child and child.type == "constant" and child.label == element:
                                matches.append({"op": n.id, "absorbing": child.id})
                                break

            elif self._spec.rewrite_action == "unwrap_double":
                # Involution: f(f(x)) → x
                for n in graph.nodes:
                    if n.type == "operator" and n.label in op_labels:
                        children = graph.outgoing(n.id)
                        if len(children) != 1:
                            continue
                        child = graph.get_node(children[0].target)
                        if (child and child.type == "operator"
                                and child.label in op_labels):
                            inner_children = graph.outgoing(child.id)
                            if len(inner_children) == 1:
                                matches.append({
                                    "outer": n.id, "inner": child.id,
                                    "target": inner_children[0].target
                                })

            elif self._spec.rewrite_action == "replace_with_identity":
                # Self-inverse: op(x, x) → identity
                for n in graph.nodes:
                    if n.type == "operator" and n.label in op_labels:
                        children = graph.outgoing(n.id)
                        if len(children) != 2:
                            continue
                        c1 = graph.get_node(children[0].target)
                        c2 = graph.get_node(children[1].target)
                        if (c1 and c2 and c1.type == c2.type
                                and c1.label == c2.label
                                and c1.type in ("variable", "constant")):
                            matches.append({
                                "op": n.id, "left": c1.id, "right": c2.id
                            })

            return matches

        def apply(self, graph, context):
            g = graph.clone()
            action = self._spec.rewrite_action

            if action == "replace_with_other_child":
                op_id = context["op"]
                el_id = context["element"]
                other_id = context["other"]
                for e in list(g.edges):
                    if e.target == op_id:
                        g.remove_edge(e.id)
                        g.add_edge(e.source, other_id, e.relationship_type)
                g.remove_node(op_id)
                g.remove_node(el_id)
                return g, -3.0

            elif action == "replace_with_absorbing":
                op_id = context["op"]
                abs_id = context["absorbing"]
                # Rewire: any parent of op → now points to abs_id (the absorbing child)
                for e in list(g.incoming(op_id)):
                    g.remove_edge(e.id)
                    g.add_edge(e.source, abs_id, e.relationship_type)
                # Remove non-absorbing children that become orphaned
                for e in list(g.outgoing(op_id)):
                    target = e.target
                    g.remove_edge(e.id)
                    if target != abs_id and not g.incoming(target):
                        g.remove_node(target)
                # Remove the operator node itself
                g.remove_node(op_id)
                return g, -3.0

            elif action == "unwrap_double":
                outer_id = context["outer"]
                inner_id = context["inner"]
                target_id = context["target"]
                for e in list(g.edges):
                    if e.target == outer_id:
                        g.remove_edge(e.id)
                        g.add_edge(e.source, target_id, e.relationship_type)
                g.remove_node(outer_id)
                g.remove_node(inner_id)
                return g, -2.0

            elif action == "replace_with_identity":
                op_id = context["op"]
                left_id = context["left"]
                right_id = context["right"]
                for e in list(g.outgoing(op_id)):
                    g.remove_edge(e.id)
                op_node = g.get_node(op_id)
                if op_node:
                    op_node.type = "constant"
                    op_node.label = self._spec.element_label
                if len(g.incoming(left_id)) == 0:
                    g.remove_node(left_id)
                if len(g.incoming(right_id)) == 0:
                    g.remove_node(right_id)
                return g, -3.0

            return g, 0.0

    return SynthTransform(spec)


# ═══════════════════════════════════════════════════════════════════════════════
#  Transform Synthesizer
# ═══════════════════════════════════════════════════════════════════════════════

class TransformSynthesizer:
    """
    Generates new transforms for target domains by instantiating
    structural skeletons with domain-specific operators.
    """

    def __init__(self, llm_bridge=None):
        self._synthesized: Dict[str, SynthesizedTransform] = {}
        self._promoted: List[str] = []
        self._llm_bridge = llm_bridge
        # Cache LLM responses to avoid repeated queries for the same domain
        self._domain_alphabets_cache: Dict[str, dict] = {}
        self.load()

    def _get_domain_alphabet(self, target_domain: str) -> dict:
        """
        Query the LLM for the alphabet (operators and identities) of a given domain.
        Uses caching to avoid repeated queries.
        """
        if not hasattr(self, "_llm_bridge") or not self._llm_bridge:
            try:
                from sare.interface import llm_bridge
                self._llm_bridge = llm_bridge
            except ImportError:
                log.error("Could not import llm_bridge for synthesizer.")
                return {}

        mapped_domain = map_domain_name(target_domain)
        if mapped_domain in self._domain_alphabets_cache:
            return self._domain_alphabets_cache[mapped_domain]

        prompt = (
            f"You are a mathematical knowledge base mapping operators for the domain of '{mapped_domain}'.\n"
            "Return a JSON object where keys are the operator symbols/names, and values define their properties.\n"
            "Format:\n"
            "{\n"
            '  "+": {"identity": "0", "absorbing": null, "type": "binary"},\n'
            '  "*": {"identity": "1", "absorbing": "0", "type": "binary"}\n'
            "}\n"
            "Include basic operators for this domain. Return ONLY valid JSON, no markdown or explanation."
        )

        try:
            raw = self._llm_bridge._call_llm(prompt)
            raw = re.sub(r"```[a-z]*", "", raw).strip().strip("`").strip()
            
            # Find JSON block
            m = re.search(r"\{.*\}", raw, re.DOTALL)
            if not m:
                log.warning(f"Failed to parse LLM alphabet for {mapped_domain}: no JSON found.")
                return {}
                
            data = json.loads(m.group(0))
            self._domain_alphabets_cache[mapped_domain] = data
            log.info(f"LLM successfully provided alphabet for domain: {mapped_domain}")
            return data
            
        except Exception as e:
            log.error(f"Error querying LLM for domain alphabet ({mapped_domain}): {e}")
            return {}

    def synthesize_for_domain(self, target_domain: str,
                               missing_roles: List[str]) -> List[SynthesizedTransform]:
        """
        Generate transforms for roles missing in target_domain by asking the LLM
        for the domain's alphabet and testing combinations.
        """
        domain_ops = self._get_domain_alphabet(target_domain)
        if not domain_ops:
            return []

        new_transforms = []

        for role in missing_roles:
            skeleton = SKELETONS.get(role)
            if not skeleton:
                continue

            # Find operators in target domain that have the required property
            for op_label, op_info in domain_ops.items():
                element = None

                if skeleton.requires == "identity" and op_info.get("identity"):
                    element = op_info["identity"]
                    rewrite = "replace_with_other_child"
                elif skeleton.requires == "absorbing" and op_info.get("absorbing"):
                    element = op_info["absorbing"]
                    rewrite = "replace_with_absorbing"
                elif skeleton.requires == "involution" and op_info.get("involution"):
                    element = None
                    rewrite = "unwrap_double"
                else:
                    continue

                # Build transform name
                name = f"synth_{target_domain}_{op_label}_{role}"
                if name in self._synthesized:
                    continue

                spec = SynthesizedTransform(
                    name=name,
                    domain=target_domain,
                    role=role,
                    operator_labels=[op_label],
                    element_label=element or "",
                    rewrite_action=rewrite,
                    confidence=0.6,
                )
                self._synthesized[name] = spec
                new_transforms.append(spec)
                log.info(f"Synthesized: {name} ({skeleton.description}) via LLM Hypothesis")

        return new_transforms

    def synthesize_all_missing(self, transfer_engine) -> List[SynthesizedTransform]:
        """
        Use the TransferEngine's cross-domain map to find all missing roles
        and synthesize transforms for them.
        """
        all_new = []
        cmap = transfer_engine.get_cross_domain_map()
        domain_coverage = cmap.get("domain_coverage", {})

        for domain, info in domain_coverage.items():
            missing = info.get("missing_roles", [])
            if missing:
                new = self.synthesize_for_domain(domain, missing)
                all_new.extend(new)

        # We no longer synthesize for all unseen DOMAIN_OPERATORS because that
        # dict is gone. We only synthesize for domains that curriculum asks for or 
        # TransferEngine knows about.

        return all_new

    def get_live_transforms(self) -> list:
        """Get promoted synthesized transforms as live Transform instances."""
        transforms = []
        for name, spec in self._synthesized.items():
            if not spec.promoted:
                continue
            try:
                t = _make_runtime_transform(spec)
                transforms.append(t)
            except Exception as e:
                log.warning(f"Failed to instantiate {name}: {e}")
        return transforms

    def get_promoted(self) -> List[str]:
        return list(self._promoted)

    def promote(self, name: str):
        if name in self._synthesized:
            self._synthesized[name].promoted = True
            self._synthesized[name].confidence = 0.9
            if name not in self._promoted:
                self._promoted.append(name)
            self.save()

    def record_test_result(self, name: str, result: dict):
        spec = self._synthesized.get(name)
        if not spec:
            return
        spec.test_results.append(dict(result))
        self.save()

    def stats(self) -> dict:
        return {
            "total_synthesized": len(self._synthesized),
            "promoted": len(self._promoted),
            "by_domain": {},
            "transforms": [s.to_dict() for s in self._synthesized.values()],
        }

    def save(self):
        try:
            _PERSIST_PATH.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "synthesized": {
                    name: {
                        "name": spec.name,
                        "domain": spec.domain,
                        "role": spec.role,
                        "operator_labels": spec.operator_labels,
                        "element_label": spec.element_label,
                        "rewrite_action": spec.rewrite_action,
                        "confidence": spec.confidence,
                        "test_results": spec.test_results,
                        "promoted": spec.promoted,
                        "created_at": spec.created_at,
                    }
                    for name, spec in self._synthesized.items()
                },
                "promoted": list(self._promoted),
            }
            _PERSIST_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        except Exception as e:
            log.warning(f"Failed to save synthesized transforms: {e}")

    def load(self):
        if not _PERSIST_PATH.exists():
            return
        try:
            payload = json.loads(_PERSIST_PATH.read_text(encoding="utf-8"))
            self._synthesized = {}
            for name, data in payload.get("synthesized", {}).items():
                if not isinstance(data, dict):
                    continue
                spec_name = data.get("name", name)
                if not spec_name or "domain" not in data or "role" not in data:
                    continue
                self._synthesized[name] = SynthesizedTransform(
                    name=spec_name,
                    domain=data["domain"],
                    role=data["role"],
                    operator_labels=list(data.get("operator_labels", [])),
                    element_label=data.get("element_label", ""),
                    rewrite_action=data.get("rewrite_action", ""),
                    confidence=float(data.get("confidence", 0.5)),
                    test_results=list(data.get("test_results", [])),
                    promoted=bool(data.get("promoted", False)),
                    created_at=float(data.get("created_at", time.time())),
                )
            self._promoted = list(payload.get("promoted", []))
        except Exception as e:
            log.warning(f"Failed to load synthesized transforms: {e}")
