"""
ConjectureEngine — AGI Leap Module
====================================
The brain's proactive hypothesis generator.

AGI systems don't just *react* to problems — they *wonder*. This module
gives SARE-HX the ability to notice patterns in its solved problems and
automatically formulate new mathematical conjectures to test.

Core loop:
  1. Watch solved problem history for structural patterns
  2. When a pattern repeats across 3+ domains → generate a *conjecture*
  3. Submit conjectures to the NegotiationArena for multi-agent validation
  4. Track proven vs. disproven conjectures (epistemic scoreboard)

The conjecture types it generates:
  - Generalization: "if a+0=a works in arithmetic, maybe it works in ALL ring-like domains"
  - Dual: "if p AND TRUE = p, then maybe p OR FALSE = p by duality"
  - Inverse: "if A rule reduces energy, does its inverse always increase it?"
  - Composition: "can rules R1 followed by R2 be collapsed to a single super-rule?"
"""

from __future__ import annotations

import hashlib
import logging
import random
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

log = logging.getLogger(__name__)


# ── Conjecture types ──────────────────────────────────────────────────────────

@dataclass
class Conjecture:
    """A hypothesis generated by the ConjectureEngine."""
    cid: str                      # unique id
    conjecture_type: str           # "generalization" | "dual" | "inverse" | "composition"
    statement: str                 # human-readable claim
    source_rules: List[str]        # rules that inspired this conjecture
    target_domain: str
    pattern_expression: str       # the test expression
    expected_result: str          # what we predict should happen
    confidence: float             # prior belief (0.0–1.0)
    status: str = "pending"       # "pending" | "proven" | "disproven" | "uncertain"
    evidence_for: int = 0
    evidence_against: int = 0
    created_at: float = field(default_factory=time.time)
    validated_at: Optional[float] = None

    @property
    def support_ratio(self) -> float:
        total = self.evidence_for + self.evidence_against
        return float(self.evidence_for) / total if total > 0 else 0.5

    def record_evidence(self, success: bool):
        if success:
            self.evidence_for += 1
        else:
            self.evidence_against += 1
        total = self.evidence_for + self.evidence_against
        # Update status based on evidence
        if total >= 3:
            ratio = self.support_ratio
            if ratio >= 0.8:
                self.status = "proven"
                self.validated_at = time.time()
            elif ratio <= 0.2:
                self.status = "disproven"
                self.validated_at = time.time()
            else:
                self.status = "uncertain"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.cid,
            "type": self.conjecture_type,
            "statement": self.statement,
            "domain": self.target_domain,
            "expression": self.pattern_expression,
            "confidence": float(int(self.confidence * 100)) / 100.0,
            "status": self.status,
            "evidence_for": self.evidence_for,
            "evidence_against": self.evidence_against,
            "support_ratio": float(int(self.support_ratio * 100)) / 100.0,
            "source_rules": self.source_rules,
        }


# ── Pattern library for conjecture generation ─────────────────────────────────

# Dual mappings: what the "dual" operator is in each domain
_DOMAIN_DUALS = {
    "arithmetic": {"add": "mul", "zero": "one"},
    "logic":      {"and": "or", "true": "false", "not": "not"},
    "sets":       {"union": "intersect", "empty": "universal"},
    "algebra":    {"add": "mul", "zero": "one"},
}

# Generalization templates: when rule X is known in domain A,
# generate expression for testing it in domain B
_GENERALIZATION_TEMPLATES = [
    # identity in arithmetic → test in logic
    {"trigger": "additive_identity", "src": "arithmetic", "dst": "logic",
     "expr": "A AND TRUE", "expected": "A",
     "statement": "If a+0=a holds in arithmetic, then A∧⊤=A should hold in logic by identity analogy"},
    {"trigger": "multiplicative_identity", "src": "arithmetic", "dst": "logic",
     "expr": "A OR FALSE", "expected": "A",
     "statement": "If a*1=a holds, then A∨⊥=A should hold by identity duality"},
    {"trigger": "additive_identity", "src": "arithmetic", "dst": "algebra",
     "expr": "x + 0", "expected": "x",
     "statement": "Additive identity should generalize from arithmetic to symbolic algebra"},
    {"trigger": "double_negation", "src": "logic", "dst": "arithmetic",
     "expr": "neg neg x", "expected": "x",
     "statement": "Double negation should generalize from logic (~~ p=p) to arithmetic (--x=x)"},
    {"trigger": "annihilator_mul", "src": "arithmetic", "dst": "logic",
     "expr": "A AND FALSE", "expected": "FALSE",
     "statement": "Annihilator (a*0=0) should generalize to logic (A∧⊥=⊥)"},
    {"trigger": "self_subtraction", "src": "arithmetic", "dst": "logic",
     "expr": "A XOR A", "expected": "FALSE",
     "statement": "Self-annihilation (a-a=0) should generalize to XOR (A⊕A=⊥)"},
]

# Composition templates: can two known rules be composed into one?
_COMPOSITION_TEMPLATES = [
    {"rules": ["additive_identity", "multiplicative_identity"],
     "expr": "(x + 0) * 1", "expected": "x",
     "statement": "Additive identity followed by multiplicative identity compose into identity"},
    {"rules": ["double_negation", "additive_identity"],
     "expr": "neg neg (x + 0)", "expected": "x",
     "statement": "Double negation and additive identity compose: ~~(x+0) = x"},
    {"rules": ["multiplicative_zero", "additive_identity"],
     "expr": "y * 0 + x", "expected": "x",
     "statement": "Annihilation and identity compose: y*0+x = 0+x = x"},
]


# ── ConjectureEngine ──────────────────────────────────────────────────────────

class ConjectureEngine:
    """
    Proactive hypothesis generator for SARE-HX.

    Watches the brain's rule discoveries and automatically generates
    plausible mathematical conjectures for validation.
    """

    def __init__(self, max_conjectures: int = 200):
        self._conjectures: List[Conjecture] = []
        self._max = max_conjectures
        self._known_rules: List[str] = []       # rules the brain has confirmed
        self._tick_count: int = 0
        self._proven_count: int = 0
        self._disproven_count: int = 0
        self._negotiation_arena = None           # wired by Brain
        self._engine_ref = None                  # wired by Brain for test-solving
        self._generated_ids: set = set()
        log.info("ConjectureEngine initialized")

    def wire(self, negotiation_arena=None, engine=None):
        """Connect to NegotiationArena and Brain for validation."""
        self._negotiation_arena = negotiation_arena
        self._engine_ref = engine

    def observe_rule(self, rule_name: str, domain: str, confidence: float):
        """Called when Brain confirms/discovers a rule. Triggers conjecture generation."""
        if rule_name not in self._known_rules:
            self._known_rules.append(rule_name)
            self._generate_from_rule(rule_name, domain, confidence)

    def _generate_from_rule(self, rule_name: str, domain: str, confidence: float):
        """Generate conjectures based on a newly confirmed rule."""
        generated = 0

        # 1. Generalization conjectures
        for tmpl in _GENERALIZATION_TEMPLATES:
            if tmpl["trigger"] in rule_name and tmpl["src"] == domain:
                cid = f"gen_{rule_name}_{tmpl['dst']}"
                if cid not in self._generated_ids:
                    c = Conjecture(
                        cid=cid,
                        conjecture_type="generalization",
                        statement=str(tmpl.get("statement", "")),
                        source_rules=[rule_name],
                        target_domain=str(tmpl.get("dst", "")),
                        pattern_expression=str(tmpl.get("expr", "")),
                        expected_result=str(tmpl.get("expected", "")),
                        confidence=min(0.85, confidence * 0.9),
                    )
                    self._add(c)
                    self._generated_ids.add(cid)
                    generated += 1

        # 2. Composition conjectures
        for tmpl in _COMPOSITION_TEMPLATES:
            if rule_name in tmpl["rules"]:
                # only generate if we know ALL rules in this composition
                if all(r in self._known_rules or r == rule_name for r in tmpl["rules"]):
                    cid = f"comp_{'_'.join(sorted(tmpl['rules']))}"
                    if cid not in self._generated_ids:
                        c = Conjecture(
                            cid=cid,
                            conjecture_type="composition",
                            statement=str(tmpl.get("statement", "")),
                            source_rules=list(tmpl.get("rules", [])),
                            target_domain=domain,
                            pattern_expression=str(tmpl.get("expr", "")),
                            expected_result=str(tmpl.get("expected", "")),
                            confidence=min(0.75, confidence * 0.8),
                        )
                        self._add(c)
                        self._generated_ids.add(cid)
                        generated += 1

        if generated > 0:
            log.info(f"ConjectureEngine: {generated} new conjectures from rule '{rule_name}'")

    def _add(self, c: Conjecture):
        self._conjectures.append(c)
        if len(self._conjectures) > self._max:
            # Remove oldest proven/disproven first
            settled = [i for i, x in enumerate(self._conjectures)
                       if x.status in ("proven", "disproven") and i != len(self._conjectures)-1]
            if settled:
                self._conjectures.pop(settled[0])
            else:
                self._conjectures.pop(0)

    def tick(self) -> dict:
        """
        Main cycle: validate pending conjectures by test-solving.
        Call this every N brain cycles.
        """
        self._tick_count += 1
        validated = 0
        proven = 0
        disproven = 0

        pending = [c for c in self._conjectures if c.status == "pending"]

        # Validate up to 3 per tick
        for conj in pending[:3]:
            result = self._validate(conj)
            if result is not None:
                conj.record_evidence(result)
                validated += 1
                if conj.status == "proven":
                    proven += 1
                    self._proven_count += 1
                    log.info(f"✅ Conjecture PROVEN: {conj.statement[:60]}")
                    # Submit proven conjecture to NegotiationArena
                    self._report_to_arena(conj)
                elif conj.status == "disproven":
                    disproven += 1
                    self._disproven_count += 1
                    log.info(f"❌ Conjecture DISPROVEN: {conj.statement[:60]}")

        # Every 50 ticks, ask LLM for novel conjectures beyond the template set
        llm_added = 0
        if self._tick_count % 50 == 0:
            llm_added = self.generate_llm_conjectures()

        return {
            "tick": self._tick_count,
            "validated": validated,
            "proven_this_tick": proven,
            "disproven_this_tick": disproven,
            "llm_conjectures_added": llm_added,
            "pending": len([c for c in self._conjectures if c.status == "pending"]),
        }

    def _validate(self, conj: Conjecture) -> Optional[bool]:
        """Try to solve the conjecture's test expression and check if it simplifies."""
        if not self._engine_ref:
            return None
        try:
            eng = self._engine_ref
            if hasattr(eng, '_engine'):
                eng = eng._engine
            if not hasattr(eng, 'solve'):
                return None
            result = eng.solve(conj.pattern_expression)
            if result is None:
                return False
            if isinstance(result, dict):
                energy_after = result.get("energy", result.get("final_energy", 1.0))
                return float(energy_after) < 0.8
            else:
                energy = getattr(result, 'energy', None)
                if energy is not None:
                    return float(energy) < 0.8
                return getattr(result, 'success', False)
        except Exception as e:
            log.debug(f"ConjectureEngine validate failed for '{conj.pattern_expression}': {e}")
            return None

    def _report_to_arena(self, conj: Conjecture):
        """Submit a proven conjecture to the NegotiationArena."""
        if not self._negotiation_arena:
            return
        try:
            # Create a minimal transform-like object for the arena
            class _MinimalTransform:
                def __init__(self, conj):
                    self.name = conj.cid
                    self.antecedent = conj.pattern_expression
                    self.consequent = conj.expected_result
                    self.confidence = conj.confidence
                    def valid(self): return True
                    self.valid = valid

            transform = _MinimalTransform(conj)
            self._negotiation_arena.submit_discovery(
                problem_signature=f"conjecture_{conj.target_domain}",
                agent_id=f"conjecture_engine",
                transform=transform,
                derivation_path=conj.source_rules,
            )
        except Exception as e:
            log.debug(f"ConjectureEngine arena report failed: {e}")

    def generate_llm_conjectures(self) -> int:
        """Ask LLM to propose novel conjectures based on known rules and domains.

        Called every ~50 ticks to go beyond the hardcoded template set.
        Returns the number of new conjectures added.
        """
        if not self._known_rules:
            return 0
        try:
            from sare.interface.llm_bridge import _call_llm
            rules_str = ", ".join(self._known_rules[-10:])
            prompt = (
                f"I am an AI that has learned these mathematical rules: {rules_str}\n"
                f"Generate 3 novel mathematical conjectures I should test next. "
                f"Each conjecture must include:\n"
                f"  - statement: a one-line claim (e.g. 'a*0+a = a for all a')\n"
                f"  - expression: a symbolic test expression (e.g. 'x*0+x')\n"
                f"  - expected: the expected simplified result (e.g. 'x')\n"
                f"  - domain: one of arithmetic/algebra/logic/sets\n"
                f"Format as JSON array of objects with these 4 fields. Return ONLY the JSON."
            )
            resp = _call_llm(prompt).strip()
            # Extract JSON array
            import re as _re, json as _json
            m = _re.search(r'\[.*\]', resp, _re.DOTALL)
            if not m:
                return 0
            items = _json.loads(m.group(0))
            added = 0
            for item in items[:3]:
                stmt = str(item.get("statement", "")).strip()
                expr = str(item.get("expression", "")).strip()
                expected = str(item.get("expected", "")).strip()
                domain = str(item.get("domain", "algebra")).strip()
                if not stmt or not expr:
                    continue
                cid = f"llm_{hashlib.sha1(stmt.encode()).hexdigest()[:8]}"
                if cid in self._generated_ids:
                    continue
                c = Conjecture(
                    cid=cid,
                    conjecture_type="generalization",
                    statement=stmt,
                    source_rules=self._known_rules[-3:],
                    target_domain=domain,
                    pattern_expression=expr,
                    expected_result=expected,
                    confidence=0.6,
                )
                self._add(c)
                self._generated_ids.add(cid)
                added += 1
            if added:
                log.info("ConjectureEngine: +%d LLM-generated conjectures", added)
            return added
        except Exception as exc:
            log.debug("ConjectureEngine LLM conjecture generation failed: %s", exc)
            return 0

    def pending_conjectures(self) -> List[Conjecture]:
        return [c for c in self._conjectures if c.status == "pending"]

    def proven_conjectures(self) -> List[Conjecture]:
        return [c for c in self._conjectures if c.status == "proven"]

    def summary(self) -> Dict[str, Any]:
        status_counts = {}
        for c in self._conjectures:
            status_counts[c.status] = status_counts.get(c.status, 0) + 1
        # Ordered list: proven first, then pending, for the dashboard
        recent = sorted(self._conjectures[-20:], key=lambda c: c.created_at, reverse=True)
        return {
            "total_conjectures": len(self._conjectures),
            "known_rules": len(self._known_rules),
            "status_breakdown": status_counts,
            "proven_total": self._proven_count,
            "disproven_total": self._disproven_count,
            "tick_count": self._tick_count,
            "recent_conjectures": [c.to_dict() for c in recent[:10]],
            "active_conjectures": [c.to_dict() for c in self.pending_conjectures()[:5]],
            "recent_pending": [c.to_dict() for c in self.pending_conjectures()[:5]],
            "recent_proven": [c.to_dict() for c in self.proven_conjectures()[-5:]],
        }
