"""
PhysicsSimulator — Upgrade 1: True World Simulation

Symbolic physics engine for SARE-HX.

Rather than a numerical physics engine (which would need rendering),
this implements SYMBOLIC physics: objects have properties, laws govern
transitions, and the engine generates symbolic expressions that the
SARE reasoning engine can then simplify/understand.

Concepts emerge naturally from simulated physics:
  - gravity → "falling objects accelerate" → d²x/dt² = -g
  - collision → "momentum conserved" → m₁v₁ + m₂v₂ = const
  - temperature → "heat flows from hot to cold" → ΔT ∝ -ΔQ/C

These become grounded examples in the ConceptGraph.
"""

from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


# ── Object Properties ──────────────────────────────────────────────────────────

@dataclass
class PhysicsObject:
    """A symbolic physics object with properties."""
    name: str
    mass: float = 1.0           # kg
    position: float = 0.0       # metres (1-D for simplicity)
    velocity: float = 0.0       # m/s
    temperature: float = 300.0  # K
    charge: float = 0.0         # C
    fluid_level: float = 0.0    # fraction 0-1 (for containers)
    properties: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "mass": round(self.mass, 3),
            "position": round(self.position, 3),
            "velocity": round(self.velocity, 3),
            "temperature": round(self.temperature, 1),
            "charge": round(self.charge, 3),
            "fluid_level": round(self.fluid_level, 3),
        }


@dataclass
class PhysicsEvent:
    """A symbolic event generated by the simulator."""
    event_type: str         # 'collision', 'free_fall', 'heat_transfer', 'fluid_flow', ...
    objects: List[str]      # names of involved objects
    law: str                # e.g. "F = m * a"
    symbolic_expr: str      # e.g. "v = sqrt(2 * g * h)"
    result: str             # English description of what happened
    concept_hint: str       # ConceptGraph concept this grounds
    domain: str             # 'mechanics', 'thermodynamics', 'electrostatics', 'fluid_dynamics'
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return {
            "event_type": self.event_type,
            "objects": self.objects,
            "law": self.law,
            "symbolic_expr": self.symbolic_expr,
            "result": self.result,
            "concept_hint": self.concept_hint,
            "domain": self.domain,
        }


# ── Physics Laws ───────────────────────────────────────────────────────────────

_G = 9.81          # gravitational acceleration m/s²
_STEFAN = 5.67e-8  # Stefan-Boltzmann constant

_PHYSICS_SCENARIOS = [
    # (scenario_name, domain, law, concept_hint)
    ("free_fall",          "mechanics",       "v² = 2*g*h",              "kinematics"),
    ("projectile_motion",  "mechanics",       "x = v₀*t + ½*a*t²",      "kinematics"),
    ("spring_energy",      "mechanics",       "E = ½*k*x²",              "potential_energy"),
    ("elastic_collision",  "mechanics",       "m₁v₁ + m₂v₂ = const",    "momentum_conservation"),
    ("inelastic_collision","mechanics",       "KE_lost = ½*μ*(Δv)²",     "energy_dissipation"),
    ("heat_conduction",    "thermodynamics",  "Q = k*A*ΔT/d",            "heat_transfer"),
    ("ideal_gas",          "thermodynamics",  "PV = nRT",                 "gas_law"),
    ("carnot_efficiency",  "thermodynamics",  "η = 1 - T_cold/T_hot",    "thermodynamic_efficiency"),
    ("ohms_law",           "electrostatics",  "V = I*R",                  "electrical_resistance"),
    ("coulombs_law",       "electrostatics",  "F = k*q₁*q₂/r²",         "electrostatic_force"),
    ("bernoulli",          "fluid_dynamics",  "P + ½ρv² + ρgh = const",  "fluid_conservation"),
    ("continuity",         "fluid_dynamics",  "A₁v₁ = A₂v₂",            "fluid_continuity"),
    ("gravity_field",      "gravity",         "g = G*M/r²",              "gravitational_field"),
    ("orbital_velocity",   "gravity",         "v = sqrt(G*M/r)",         "orbital_mechanics"),
    ("buoyancy",           "fluid_dynamics",  "F = ρ*g*V",               "archimedes_principle"),
]


class PhysicsSimulator:
    """
    Symbolic physics engine for SARE-HX.

    Generates physics events (grounded observations) that feed into
    the ConceptGraph, giving the system intuitions about:
      - How gravity works (falling objects, orbits)
      - How collisions work (momentum, energy)
      - How heat flows (thermodynamics)
      - How fluids behave (Bernoulli, continuity)
      - How charges interact (Coulomb, Ohm)

    This grounds abstract mathematical rules in physical intuition —
    exactly how biological intelligence develops physics understanding.
    """

    def __init__(self):
        self._objects: Dict[str, PhysicsObject] = {}
        self._events: List[PhysicsEvent] = []
        self._tick: int = 0
        self._seed_objects()

    def _seed_objects(self):
        """Create a small default world."""
        self._objects = {
            "ball":     PhysicsObject("ball",     mass=0.5, position=10.0, velocity=0.0, temperature=300.0),
            "block":    PhysicsObject("block",    mass=2.0, position=0.0,  velocity=5.0, temperature=320.0),
            "fluid_A":  PhysicsObject("fluid_A",  mass=1.0, position=0.0,  velocity=2.0, temperature=350.0, fluid_level=0.8),
            "fluid_B":  PhysicsObject("fluid_B",  mass=1.0, position=0.0,  velocity=0.0, temperature=280.0, fluid_level=0.3),
            "charge_p": PhysicsObject("charge_p", mass=0.001, position=0.1, charge=1.6e-19),
            "charge_n": PhysicsObject("charge_n", mass=0.001, position=0.2, charge=-1.6e-19),
        }

    # ── Simulation steps ────────────────────────────────────────────────────────

    def simulate_free_fall(self, obj_name: str = "ball") -> PhysicsEvent:
        """Simulate an object falling under gravity."""
        obj = self._objects.get(obj_name, PhysicsObject("ball", mass=0.5, position=10.0))
        h = abs(obj.position)
        v_final = math.sqrt(2 * _G * h) if h > 0 else 0.0
        t_fall = math.sqrt(2 * h / _G) if h > 0 else 0.0
        obj.velocity = -v_final
        expr = f"v = sqrt(2 * {_G} * {h:.1f}) = {v_final:.2f} m/s"
        return PhysicsEvent(
            event_type="free_fall",
            objects=[obj_name],
            law="v² = 2*g*h",
            symbolic_expr=expr,
            result=f"{obj_name} falls {h:.1f}m, reaches {v_final:.2f} m/s after {t_fall:.2f}s",
            concept_hint="kinematics",
            domain="mechanics",
        )

    def simulate_collision(self, a_name: str = "ball", b_name: str = "block") -> PhysicsEvent:
        """Simulate elastic collision: m₁v₁ + m₂v₂ = m₁v₁' + m₂v₂'"""
        a = self._objects.get(a_name, PhysicsObject("ball", mass=0.5, velocity=3.0))
        b = self._objects.get(b_name, PhysicsObject("block", mass=2.0, velocity=0.0))
        p_before = a.mass * a.velocity + b.mass * b.velocity
        # Elastic collision formulas
        v_a_after = ((a.mass - b.mass) * a.velocity + 2 * b.mass * b.velocity) / (a.mass + b.mass)
        v_b_after = ((b.mass - a.mass) * b.velocity + 2 * a.mass * a.velocity) / (a.mass + b.mass)
        p_after = a.mass * v_a_after + b.mass * v_b_after
        a.velocity = v_a_after
        b.velocity = v_b_after
        expr = f"p_before={p_before:.3f} kg·m/s, p_after={p_after:.3f} kg·m/s (conserved)"
        return PhysicsEvent(
            event_type="elastic_collision",
            objects=[a_name, b_name],
            law="m₁v₁ + m₂v₂ = m₁v₁' + m₂v₂'",
            symbolic_expr=expr,
            result=f"{a_name}→{v_a_after:.2f} m/s, {b_name}→{v_b_after:.2f} m/s; momentum conserved",
            concept_hint="momentum_conservation",
            domain="mechanics",
        )

    def simulate_heat_transfer(self, hot_name: str = "fluid_A", cold_name: str = "fluid_B") -> PhysicsEvent:
        """Simulate heat flow from hot to cold object."""
        hot = self._objects.get(hot_name, PhysicsObject("hot", temperature=350.0, mass=1.0))
        cold = self._objects.get(cold_name, PhysicsObject("cold", temperature=280.0, mass=1.0))
        delta_t = hot.temperature - cold.temperature
        c_specific = 4186.0  # J/(kg·K) water
        q_transfer = 0.1 * c_specific * delta_t  # 10% transfer per step
        t_eq = (hot.mass * hot.temperature + cold.mass * cold.temperature) / (hot.mass + cold.mass)
        hot.temperature -= q_transfer / (hot.mass * c_specific)
        cold.temperature += q_transfer / (cold.mass * c_specific)
        expr = f"Q = 0.1 * {c_specific} * {delta_t:.1f} = {q_transfer:.1f} J; T_eq → {t_eq:.1f} K"
        return PhysicsEvent(
            event_type="heat_transfer",
            objects=[hot_name, cold_name],
            law="Q = m*c*ΔT; heat flows hot→cold",
            symbolic_expr=expr,
            result=f"Heat flows from {hot_name}({hot.temperature+q_transfer/(hot.mass*c_specific):.0f}K) to {cold_name}; equilibrium at {t_eq:.0f}K",
            concept_hint="heat_transfer",
            domain="thermodynamics",
        )

    def simulate_fluid_flow(self, a_name: str = "fluid_A", b_name: str = "fluid_B") -> PhysicsEvent:
        """Simulate fluid flow: continuity equation A₁v₁ = A₂v₂"""
        a = self._objects.get(a_name, PhysicsObject("fluid_A", velocity=2.0, fluid_level=0.8))
        b = self._objects.get(b_name, PhysicsObject("fluid_B", velocity=0.5, fluid_level=0.3))
        a1, a2 = a.fluid_level, max(b.fluid_level, 0.1)
        v2 = (a1 * a.velocity) / a2 if a2 > 0 else 0
        expr = f"A₁v₁ = {a1:.2f}*{a.velocity:.2f} = {a2:.2f}*{v2:.2f} = A₂v₂"
        return PhysicsEvent(
            event_type="fluid_continuity",
            objects=[a_name, b_name],
            law="A₁v₁ = A₂v₂ (continuity)",
            symbolic_expr=expr,
            result=f"Fluid narrows: v increases from {a.velocity:.2f} to {v2:.2f} m/s",
            concept_hint="fluid_continuity",
            domain="fluid_dynamics",
        )

    def simulate_gravity_field(self, mass: float = 5.97e24, radius: float = 6.37e6) -> PhysicsEvent:
        """Simulate gravitational field: g = G*M/r²"""
        G = 6.674e-11
        g = G * mass / (radius ** 2)
        v_orbital = math.sqrt(G * mass / radius)
        expr = f"g = G*M/r² = {G}*{mass:.2e}/{radius:.2e}² = {g:.2f} m/s²"
        return PhysicsEvent(
            event_type="gravity_field",
            objects=["planet"],
            law="g = G*M/r²",
            symbolic_expr=expr,
            result=f"Surface gravity {g:.2f} m/s²; orbital velocity {v_orbital:.0f} m/s",
            concept_hint="gravitational_field",
            domain="gravity",
        )

    # ── Batch simulation ────────────────────────────────────────────────────────

    def run_session(self, n_events: int = 10) -> List[PhysicsEvent]:
        """Run a mixed physics session, generating n_events."""
        simulators = [
            self.simulate_free_fall,
            self.simulate_collision,
            self.simulate_heat_transfer,
            self.simulate_fluid_flow,
            self.simulate_gravity_field,
        ]
        events = []
        for i in range(n_events):
            fn = simulators[i % len(simulators)]
            try:
                ev = fn()
                events.append(ev)
                self._events.append(ev)
            except Exception:
                pass
        self._tick += 1
        return events

    def feed_to_concept_graph(self, cg) -> int:
        """
        Feed all accumulated physics events into a ConceptGraph
        as grounded examples.  Returns number of examples added.
        """
        count = 0
        for ev in self._events[-20:]:  # last 20 events
            try:
                cg.ground_example(
                    concept_name=ev.concept_hint,
                    text=ev.result,
                    operation=ev.event_type,
                    inputs=[ev.law],
                    result=ev.symbolic_expr,
                    domain=ev.domain,
                    symbolic=ev.symbolic_expr,
                )
                count += 1
            except Exception:
                pass
        return count

    def symbolic_rules(self) -> List[Tuple[str, str]]:
        """Return (concept_hint, symbolic_rule) pairs derived from physics laws."""
        return [(s[3], s[2]) for s in _PHYSICS_SCENARIOS]

    def summary(self) -> dict:
        return {
            "objects": len(self._objects),
            "total_events": len(self._events),
            "ticks": self._tick,
            "domains": list({ev.domain for ev in self._events}),
            "recent_events": [ev.to_dict() for ev in self._events[-5:]],
        }
